services:
  constype-unit-tests:
    container_name: constype-unit-tests
    build: .
    working_dir: /src/tests
    command: lua ./all.lua

  constype:
    container_name: constype
    build: .
    depends_on:
      constype-unit-tests:
        condition: service_completed_successfully
    working_dir: /src/app
    command: lua ./main.lua
    stdin_open: true
    tty: true
    volumes:
      - ./persistent/:/texts
    environment:
      - COLOR_DEFAULT_IDX=0
      - COLOR_SUCC_IDX=92
      - COLOR_FAIL_IDX=91
      - COLOR_FIXED_IDX=93


        # reset   = 0
        # black   = 30 (90 for bright)
        # red     = 31 (91 for bright)
        # green   = 32 (92 for bright)
        # yellow  = 33 (93 for bright)
        # blue    = 34 (94 for bright)
        # magenta = 35 (95 for bright)
        # cyan    = 36 (96 for bright)
        # white   = 37 (97 for bright)
