version: '3'

services:
  constype-unit-tests:
    container_name: constype-unit-tests
    build: .
    working_dir: /src/tests
    command: lua ./all.lua

  constype:
    container_name: constype
    build: .
    depends_on:
      constype-unit-tests:
        condition: service_completed_successfully
    working_dir: /src/app
    command: lua ./main.lua
    stdin_open: true
    tty: true
    volumes:
      - ./persistent/:/pers
    environment:
      - COLOR_DEFAULT_IDX=0
      - COLOR_SUCC_IDX=32
      - COLOR_FAIL_IDX=33
      - COLOR_FIXED_IDX=34


        # reset = 0
        # black = 30
        # red = 31
        # green = 32
        # yellow = 33
        # blue = 34
        # magenta = 35
        # cyan = 36
        # white = 37
