services:
  userclient-db:
    container_name: constype-db
    image: postgres:alpine
    restart: always
    user: root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 2s
      retries: 10
    ports:
      - 15432:5432
    environment:
      - POSTGRES_DB=constype-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  constype-unit-tests:
    container_name: constype-unit-tests
    build: .
    working_dir: /src/tests
    command: lua ./all.lua

  seeder:
    container_name: seeder
    build: .
    depends_on:
      constype-unit-tests:
        condition: service_completed_successfully
      userclient-db:
        condition: service_healthy
    working_dir: /src/app
    command: lua ./seed.lua
    # stdin_open: true
    # tty: true
    volumes:
      - ./persistent/:/texts
    env_file:
      - .env

  constype:
    container_name: constype
    build: .
    depends_on:
      constype-unit-tests:
        condition: service_completed_successfully
      userclient-db:
        condition: service_healthy
    working_dir: /src/app
    command: lua ./main.lua
    stdin_open: true
    tty: true
    volumes:
      - ./persistent/:/texts
    env_file:
      - .env

    # reset   = 0
    # black   = 30 (90 for bright)
    # red     = 31 (91 for bright)
    # green   = 32 (92 for bright)
    # yellow  = 33 (93 for bright)
    # blue    = 34 (94 for bright)
    # magenta = 35 (95 for bright)
    # cyan    = 36 (96 for bright)
    # white   = 37 (97 for bright)
